repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check . --fix
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
